### ISSUE TITLE
:sparkles: feat: 채팅 기능 구현 

### ISSUE THREAD

**Issue by sma96** [42-ios-piscine-project/example-code#5]
- [ ] 채팅기능 구조 조사
- [ ] Firebase 기초 문법 숙지(로그인, 데이터 추가 및 읽기)
- [x] Figma study
- [x] 맵 팝업창에서 팡해요 리스트로 뷰 전환
- [ ] 채팡해요 단체 채팅방 리스트만들기
- [ ] 개인 dm 채팅방 리스트만들기
- [ ] 채팅방 구현

**Comment by dq-QQQ** [comment]
good
