### ISSUE TITLE
✨ feat: 맵 기능

### ISSUE THREAD

**Issue by JJunghyunY** [42-ios-piscine-project/example-code#8]
## 맵 기능 구현
 - [x] 커스텀 팝업
 - [x] 받아와서 마킹
 - [ ] 모달 창(컬렉션 뷰, 메뉴 추천 등등)
 - [x] 핀 주소를 파싱
 - [ ] 어노테이션 클러스터링
 - [x] 최대 줌

**Comment by chanhihi** [comment]
v1 마무리 후 v2에서 남은 이슈들 처리예정
